name: Build Test
permissions:
  contents: write
on:
  push:
    branches:
      - init

jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
    env:
      RCV: -dev
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential \
          libcriterion-dev \
          iputils-ping
    - name: Build
      run: |
          ./bootstrap.sh
          ./configure
          make
          make check
          make deb
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-file
        path: |
          dist/ssmdnsd_*.deb
