name: Release
permissions:
  contents: write
on:
  push:
    branches:
      - test
jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Variables and stuff
      run: |
        VER=$(grep -Po '(?<=(^version=)).*' proj | tr -d '\n')
        echo "VERSION=$VER" >> $GITHUB_ENV    
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential
    - name: Build
      run: |
          ./bootstrap.sh
          ./configure
          make
          make deb
    - name: Release
      uses: softprops/action-gh-release@v2
#      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ env.VERSION }}
        files: |
          dist/ssmdnsd_*.deb
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
